#!/bin/bash
set -e
IP="$(ifconfig utun2 | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2)"
printf "\e[33mConnecting to remote docker\e[0m\n" 1>&2
ssh root@nic-remote-docker1.fyre.ibm.com "sh sshfs.sh ${IP}"
printf "Running command: \e[95mdocker %s\e[0m\n" "$*" 1>&2
/usr/local/bin/docker "${@}"