#!/bin/bash
ENV_FILE="/tmp/.env"
ARGS=()

if [ -n "${DOCKER_ARGS}" ]; then
IFS=' ' read -r -a ARGS <<< "${DOCKER_ARGS}"
fi

CMD=("$@")

len=${#CMD[@]}
ENVVARS=("--env-file" "${ENV_FILE}")
for i in "${!CMD[@]}"; do
   if [[ "${CMD[$i]}" = "run" ]]; then
       env | grep -Ev "PATH|JAVA|HOME" > "${ENV_FILE}"  
       (( offset=len-i-1 ))
       CMD=("${CMD[@]:0:i+1}" \
       -v "${HOME}/.gitconfig:/.gitconfig":.gitconfig \
     "${ARGS[@]}"  "${ENVVARS[@]}" \
     --init \
     "${CMD[@]: -offset}")
       break
   fi
done
/usr/local/bin/docker "${CMD[@]}"
RC=$?

exit $RC;