#!/bin/bash
BASE="$(dirname "${BASH_SOURCE[0]}")"

EXPOSE_PORT=()

if [ -n "${PORT}" ]; then
EXPOSE_PORT=(-p "${PORT}:${PORT}")
fi

docker run -it "${EXPOSE_PORT[@]}" -v node_modules:/usr/local/lib/node_modules:delegated -v "/var/folders":"/var/folders" -w "${PWD}" --security-opt seccomp="${BASE}/chrome_seccomp.json"  -e npm_config_cache="${HOME}/.npm"  -e npm_config_userconfig="${HOME}/.npmrc" \
localhost:5000/node sh -c "${*}"
