#!/bin/bash

VOLUMES=${HOME}/volumes
USER_HOME="/home/node"

docker run \
-i \
--network host \
-v "${VOLUMES}/yarn":"${USER_HOME}/yarn" \
-v "${VOLUMES}/npm":"${USER_HOME}/npm" \
-v "${VOLUMES}/cache":"${USER_HOME}/.cache" \
-v "${VOLUMES}/pnpm":/pnpm \
-v "${VOLUMES}/var/folders":/var/folders \
-v "${HOME}/.gitconfig":"${USER_HOME}/.gitconfig" -v "${HOME}/.gitmessage":"${USER_HOME}/.gitmessage" \
-v "${HOME}/.npmrc":"${USER_HOME}/.npmrc"  \
-v "${PWD}":"${PWD}" \
-w "${PWD}" \
-e npm_config_cache="${USER_HOME}/npm/.npm" -e npm_config_userconfig="${USER_HOME}/.npmrc" -e npm_config_prefix="${USER_HOME}/npm/.global" \
-e YARN_CACHE_FOLDER="${USER_HOME}/yarn/.cache" -e YARN_GLOBAL_FOLDER="${USER_HOME}/yarn/.global" \
localhost:5000/node "${@}"